#!/bin/bash

gulp realdeploylive --aus
gulp realdeploylive --arg
gulp realdeploylive --can
gulp realdeploylive --eng
gulp realdeploylive --fij
gulp realdeploylive --fra
gulp realdeploylive --geo
gulp realdeploylive --ire
gulp realdeploylive --jpn
gulp realdeploylive --nam
gulp realdeploylive --nz
gulp realdeploylive --rsa
gulp realdeploylive --rus
gulp realdeploylive --sam
gulp realdeploylive --sco
gulp realdeploylive --ton
gulp realdeploylive --uru
gulp realdeploylive --usa
gulp realdeploylive --wal
gulp realdeploylive --ita